// This file is auto-generated by @hey-api/openapi-ts

import type { GetProjectsResponse } from './types.gen';

const projectSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    if (data.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    return data;
};

export const getProjectsResponseTransformer = async (data: any): Promise<GetProjectsResponse> => {
    data.items = data.items.map((item: any) => {
        return projectSchemaResponseTransformer(item);
    });
    return data;
};